### PR TITLE
input type=file may be dangerous

### PR DESCRIPTION
**Pull request by ondra-novak**
Current implementation of the extension of  /input type="file"/  (described here: https://github.com/rogerwang/node-webkit/wiki/File-dialogs) can be dangerous and it can raise several security issues. I suggest to complete rollback this extension and implement it by different way. 

My opinion is that file-dialogs extension is one of the worst feature. You should complette avoid it.

I also disabled emulation of user guestures. To give scripts ability to emulate the user is also huge security issue.

### CODE REVIEW

**Comment by rogerwang** [comment]
Thanks for contributing patches!

The operation should be enabled in Node frame to support a difference security model beyond browser.
https://github.com/rogerwang/node-webkit/wiki/Security

And it should be disabled for Normal frames, see
https://github.com/rogerwang/blink/blob/nw/Source/bindings/core/v8/custom/V8FileCustom.cpp#L51

**Comment by ondra-novak** [comment]
Unfortunately, this is not reflected in source code. You can access "file.path" property on ordinary created input file element inside a normal frame. You can also set value of that element that violates W3C standard. Value of that element returns complete path, not fakepath as it is usual (despite on frame type). Also gestures checking is disabled globally, nothing checks whether frame is node-js or not.

I found these issues thank to following article  (translated from czech language)

https://translate.google.com/translate?sl=cs&tl=en&js=y&prev=_t&hl=cs&ie=UTF-8&u=http%3A%2F%2Fjedenbod.cz%2F1583-seznam-cz-prohlizec.html&edit-text=

**Comment by rogerwang** [comment]
Then the correct fix should be disabling it and keep the standard in normal frame, but keep it enabled in Node frame. Not by simply removing it.

**Comment by rogerwang** [comment]
btw, you can also access "file.path" property and set it in Chrome browser.

``` html
<html>
<head><title>file</title>
<script>
function test() {
   var f = document.getElementById('f0');
   console.log("path: ", f.path);
   f.path = '/usr/bin/ls';
   console.log("path: ", f.path);
}
</script>
</head>
<body>
<input type="file" id="f0"></input>
<button onclick="test();">test</button>
</body></html>
```

**Comment by ondra-novak** [comment]
Sorry, I will no longer to contribute on this project due incompetence of its maintainer.

**Comment by rogerwang** [comment]
We treat security issues seriously. The last valid security report got fixed and delivered in ~2 hours.

**Comment by rogerwang** [comment]
The fix for the case http://jsfiddle.net/0104bhnc/1/

can be downloaded here: http://dl.node-webkit.org/live-build/12-28-2014/0796d42-d8ecacd-a1cc175-f2f89e2-d9a9d39-cdd879e/

**Comment by ondra-novak** [comment]
Thank you. Now it looks more accurate. I appreciate UserGestureIndicator.cpp has been rollbacked to the original version because it had potential to affect other parts of the WebKit - and I have no knowledge about all places where this flag is tested. Now that only file-picker has ability to be invoked using emulated mouse-click but just inside frame marked as node-js-frame. That is correct behaviour.

**Pull request closed without merging**
